#!/bin/bash
set -e
mkdir -p /var/lib/acs-cpp
chmod 0755 /var/lib/acs-cpp
update-desktop-database -q /usr/share/applications 2>/dev/null || true
gtk-update-icon-cache -q /usr/share/icons/hicolor 2>/dev/null || true
exit 0
